### PR TITLE
Adds handling of OPTIONS requests and Cross origin requests

### PR DESCRIPTION
**Pull request by zaidhusseini**
@zokir please see updates to handle OPTIONS requests and Cross origin requests

### CODE REVIEW

**Comment by armmimic** [comment]
@zaidhusseini Thank you for the PR. For the review process, please raise an issue first and assign yourself, then use the issue # in your PR message.

**Comment by zaidhusseini** [comment]
Hi - I already mentioned this specific issue to Zokir. Just need it to unblock some of the referral work.

Thanks,
Zaid

**Comment by armmimic** [comment]
@zaidhusseini It's best if it was mentioned here as well.

**Comment by zaidhusseini** [comment]
Sounds good - where can I raise issues/assign myself? Is there a task management tool we are using (eg, pivotal) or directly in github?

**Pull request merged**
